### ISSUE TITLE
Django-cities-light

### ISSUE THREAD

**Issue by infohata** [hospitalityclub/hc-django#4]
Instead of reinventing this bicycle, I suggest to reuse the Django Cities Light app:
[Django Cities Light](https://github.com/yourlabs/django-cities-light)

and then add the missing data from our dataset. If you agree, I'm implementing it right away.

The advantage of using it:

* global dataset of cities is maintained and being updated on daily basis at [GeoNames.org](http://www.geonames.org/).
* Django cities light data structure has all the fields we need except denormalized member stats, which we can have on a separate model (it's normal in Django), or we can extend(!) the table in our #3 core app. 

@vkuehne - the decision is yours

**Comment by vkuehne** [comment]
Love it!!!! That's what I was hoping for, that the web and tools have advanced a lot - we built our geographic database from scratch. Had a look at geonames and django-cities-light, looks awesome!

One thing to keep in mind for our geographic database is that it was quite rigid (country==>region==>city) and it would be great to have a bit more flexibility (some big cities could use another level, and in very small places regions sometimes don't make sense) so we could add or remove levels based on the feedback of our members there.

**Comment by infohata** [comment]
implemented in `hc-3-core-app-data-model` branch
